# Copyright 2021 Marcelo Henrique Neppel
# See LICENSE file for licensing details.

options:
  whitelist:
    default: ""
    description: |
      Comma-separated whitelist of IP addresses,
      IP ranges, CIDR ranges, or hostnames for hosts
      from which admin operations can be initiated.
    type: string
